-- MySQL Script generated by MySQL Workbench
-- lun 16 jun 2025 23:37:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Universidad` DEFAULT CHARACTER SET utf8 ;
USE `Universidad` ;



-- -----------------------------------------------------
-- Table `Universidad`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`persona` (
  `idpersona` VARCHAR(38) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `dni` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `domicilio` VARCHAR(100) NOT NULL,
  `telefonoAlternativo` VARCHAR(20) NULL DEFAULT NULL,
  `genero` ENUM('M', 'F', 'Otro') NOT NULL,
  `discapacidad` VARCHAR(100) NULL DEFAULT NULL,
  UNIQUE INDEX `uidx_persona_dni` (`dni` ASC) VISIBLE,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`estudiante` (
  `idpersona` VARCHAR(38) NOT NULL,
  `credito` INT NOT NULL DEFAULT 0,
  `notaPromedio` DECIMAL(4,2) NOT NULL DEFAULT 0.00,
  `carrera_id` VARCHAR(38) NOT NULL,
  `materiasAprobadas` INT NOT NULL DEFAULT 0,
  `fechaIngreso` DATE NOT NULL,
  `estadoAcademico` ENUM('ACTIVO', 'EGRESADO', 'REGULAR', 'LIBRE') NOT NULL,
  `becado` TINYINT(1) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_estudiante_carrera` (`carrera_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `Universidad`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estudiante_carrera`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `Universidad`.`carrera` (`idcarrera`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`empleado` (
  `persona` VARCHAR(38) NOT NULL,
  `titulo` VARCHAR(50) NULL DEFAULT NULL,
  `fechaIngreso` DATE NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `situacionLaboral` VARCHAR(60) NOT NULL,
  `estado` ENUM("Activo", "LICENCIA", "DESPEDIDO") NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`persona`),
  CONSTRAINT `fk_empleado_persona`
    FOREIGN KEY (`persona`)
    REFERENCES `Universidad`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`profesor` (
  `empleado_id` VARCHAR(38) NOT NULL,
  `horaInicioDisponible` TIME NOT NULL,
  `horaFinDisponible` TIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`empleado_id`),
  CONSTRAINT `fk_profesor_empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Universidad`.`empleado` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`administrativo` (
  `empleado_id` VARCHAR(38) NOT NULL,
  `sector` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `legajo` INT NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `estado` ENUM('activo', 'licencia', 'baja') NOT NULL DEFAULT 'activo',
  `turno` ENUM('mañana', 'tarde', 'noche') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`empleado_id`),
  UNIQUE INDEX `uidx_administrativo_legajo` (`legajo` ASC) VISIBLE,
  CONSTRAINT `fk_administrativo_empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Universidad`.`empleado` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `Universidad`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`Usuario` (
  `persona` VARCHAR(38) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `permisos` VARCHAR(45) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `fotoPerfilUrl` VARCHAR(2038) NULL,
  `password` VARCHAR(300) BINARY NOT NULL,
  `ultimo_login` DATETIME NULL,
  `activo` TINYINT(1) NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `fk_Usuario_persona1_idx` (`persona` ASC) VISIBLE,
  PRIMARY KEY (`persona`),
  CONSTRAINT `fk_Usuario_persona1`
    FOREIGN KEY (`persona`)
    REFERENCES `Universidad`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
