-- MySQL Script generated by MySQL Workbench
-- sáb 07 jun 2025 13:28:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Universidad` ;
-- -----------------------------------------------------
-- Schema Universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Universidad` ;
USE `Universidad` ;

-- -----------------------------------------------------
-- Table `Universidad`.`delegacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`delegacion` (
  `iddelegacion` VARCHAR(38) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `provincia` VARCHAR(35) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`iddelegacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`facultad` (
  `idfacultad` INT NOT NULL AUTO_INCREMENT,
  `nombreFacultad` VARCHAR(100) NOT NULL,
  `telefono` INT NOT NULL,
  `emil` VARCHAR(100) NOT NULL,
  `decano` VARCHAR(100) NOT NULL,
  `delegacion_iddelegacion` VARCHAR(38) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `cantidad_carreras` INT NOT NULL DEFAULT 0,
  `direccion` VARCHAR(100) NOT NULL,
  `logo_url` VARCHAR(2083) NULL,
  `horario_atencion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idfacultad`, `delegacion_iddelegacion`),
  UNIQUE INDEX `nombreFacultad_UNIQUE` (`nombreFacultad` ASC) VISIBLE,
  INDEX `fk_facultad_delegacion1_idx` (`delegacion_iddelegacion` ASC) VISIBLE,
  CONSTRAINT `fk_facultad_delegacion1`
    FOREIGN KEY (`delegacion_iddelegacion`)
    REFERENCES `Universidad`.`delegacion` (`iddelegacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidad`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`carrera` (
  `idcarrera` VARCHAR(38) NOT NULL,
  `facultad_id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `tituloIntermedio` VARCHAR(45) NULL DEFAULT NULL,
  `creditoCarrera` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `modalidad` ENUM('presencial', 'virtual', 'mixta') NOT NULL,
  `cantidad_materias` INT NOT NULL,
  `carga_horaria_total` INT NOT NULL,
  `plan_estudios_url` VARCHAR(2083) NULL DEFAULT NULL,
  `resolucion_oficial` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `facultad_idfacultad` INT NOT NULL,
  `facultad_delegacion_iddelegacion` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`idcarrera`, `facultad_idfacultad`, `facultad_delegacion_iddelegacion`),
  INDEX `fk_carrera_facultad1_idx` (`facultad_idfacultad` ASC, `facultad_delegacion_iddelegacion` ASC) VISIBLE,
  CONSTRAINT `fk_carrera_facultad1`
    FOREIGN KEY (`facultad_idfacultad` , `facultad_delegacion_iddelegacion`)
    REFERENCES `Universidad`.`facultad` (`idfacultad` , `delegacion_iddelegacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`materia` (
  `idmateria` VARCHAR(38) NOT NULL,
  `carrera_id` VARCHAR(38) NOT NULL,
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `credito` INT NOT NULL,
  `opcional` TINYINT(1) NOT NULL DEFAULT 0,
  `horas_totales` INT NOT NULL,
  `anio` INT NOT NULL,
  `semestre` ENUM('1', '2') NOT NULL,
  `tipo` ENUM('obligatoria', 'optativa') NOT NULL,
  `modalidad` ENUM('presencial', 'virtual', 'mixta') NOT NULL,
  `estado` ENUM('activa', 'inactiva') NOT NULL DEFAULT 'activa',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idmateria`),
  UNIQUE INDEX `uidx_materia_codigo` (`codigo` ASC) VISIBLE,
  INDEX `idx_materia_carrera` (`carrera_id` ASC) VISIBLE,
  CONSTRAINT `fk_materia_carrera`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `Universidad`.`carrera` (`idcarrera`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`correlatividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`correlatividad` (
  `idcorrelativa` INT NOT NULL AUTO_INCREMENT,
  `materia_id` VARCHAR(38) NOT NULL,
  `requisito_id` VARCHAR(38) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcorrelativa`),
  INDEX `idx_corr_materia` (`materia_id` ASC) VISIBLE,
  INDEX `idx_corr_requisito` (`requisito_id` ASC) VISIBLE,
  CONSTRAINT `fk_corr_materia`
    FOREIGN KEY (`materia_id`)
    REFERENCES `Universidad`.`materia` (`idmateria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_corr_requisito`
    FOREIGN KEY (`requisito_id`)
    REFERENCES `Universidad`.`materia` (`idmateria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`plan_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`plan_estudio` (
  `idplan` INT NOT NULL AUTO_INCREMENT,
  `carrera_id` VARCHAR(38) NOT NULL,
  `version` VARCHAR(20) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATE NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idplan`),
  INDEX `idx_plan_carrera` (`carrera_id` ASC) VISIBLE,
  CONSTRAINT `fk_plan_carrera`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `Universidad`.`carrera` (`idcarrera`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`persona` (
  `idpersona` VARCHAR(38) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `dni` VARCHAR(20) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `domicilio` VARCHAR(100) NOT NULL,
  `telefonoAlternativo` VARCHAR(20) NULL DEFAULT NULL,
  `genero` ENUM('M', 'F', 'Otro') NOT NULL,
  `discapacidad` VARCHAR(100) NULL DEFAULT NULL,
  `fotoPerfilUrl` VARCHAR(2083) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `uidx_persona_dni` (`dni` ASC) VISIBLE,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`estudiante` (
  `idpersona` VARCHAR(38) NOT NULL,
  `credito` INT NOT NULL DEFAULT 0,
  `notaPromedio` DECIMAL(3,2) NOT NULL DEFAULT 0.00,
  `carrera_id` VARCHAR(38) NOT NULL,
  `materiasAprobadas` INT NOT NULL DEFAULT 0,
  `fechaIngreso` DATE NOT NULL,
  `estadoAcademico` ENUM('ACTIVO', 'EGRESADO', 'REGULAR', 'LIBRE') NOT NULL,
  `becado` TINYINT(1) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_estudiante_carrera` (`carrera_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `Universidad`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estudiante_carrera`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `Universidad`.`carrera` (`idcarrera`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`empleado` (
  `persona` VARCHAR(38) NOT NULL,
  `titulo` VARCHAR(50) NULL DEFAULT NULL,
  `fechaIngreso` DATE NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `situacionLaboral` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`persona`),
  CONSTRAINT `fk_empleado_persona`
    FOREIGN KEY (`persona`)
    REFERENCES `Universidad`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`profesor` (
  `empleado_id` VARCHAR(38) NOT NULL,
  `horaInicioDisponible` TIME NOT NULL,
  `horaFinDisponible` TIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`empleado_id`),
  CONSTRAINT `fk_profesor_empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Universidad`.`empleado` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`administrativo` (
  `empleado_id` VARCHAR(38) NOT NULL,
  `sector` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `legajo` INT NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `estado` ENUM('activo', 'licencia', 'baja') NOT NULL DEFAULT 'activo',
  `turno` ENUM('mañana', 'tarde', 'noche') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`empleado_id`),
  UNIQUE INDEX `uidx_administrativo_legajo` (`legajo` ASC) VISIBLE,
  CONSTRAINT `fk_administrativo_empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Universidad`.`empleado` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`dia` (
  `fecha` DATE NOT NULL,
  `nombreDia` VARCHAR(35) NOT NULL,
  `diaLaboral` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`clase` (
  `idclase` VARCHAR(38) NOT NULL,
  `estudiante_id` VARCHAR(38) NOT NULL,
  `dia` DATE NOT NULL,
  `profesor_id` VARCHAR(38) NOT NULL,
  `aula` VARCHAR(10) NOT NULL,
  `materia_id` VARCHAR(38) NOT NULL,
  `numeroAlumnos` INT NOT NULL,
  `horaEntrada` TIME NOT NULL,
  `horaSalida` TIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idclase`),
  INDEX `idx_clase_estudiante` (`estudiante_id` ASC) VISIBLE,
  INDEX `idx_clase_profesor` (`profesor_id` ASC) VISIBLE,
  INDEX `idx_clase_materia` (`materia_id` ASC) VISIBLE,
  INDEX `idx_clase_dia` (`dia` ASC) VISIBLE,
  CONSTRAINT `fk_clase_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `Universidad`.`estudiante` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clase_dia`
    FOREIGN KEY (`dia`)
    REFERENCES `Universidad`.`dia` (`fecha`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clase_profesor`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `Universidad`.`profesor` (`empleado_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clase_materia`
    FOREIGN KEY (`materia_id`)
    REFERENCES `Universidad`.`materia` (`idmateria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8 PARTITION BY RANGE(YEAR(dia)) PARTITIONS 4( PARTITION p2023 VALUES LESS THAN (2024),  PARTITION p2024 VALUES LESS THAN (2025),  PARTITION p2025 VALUES LESS THAN (2026),  PARTITION pMax VALUES LESS THAN (MAX_VALUE)) ;


-- -----------------------------------------------------
-- Table `Universidad`.`horario_clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`horario_clase` (
  `idhorario` VARCHAR(38) NOT NULL,
  `idclase` VARCHAR(38) NOT NULL,
  `dia` DATE NOT NULL,
  `horaEntrada` TIME NOT NULL,
  `horaSalida` TIME NOT NULL,
  `aula` VARCHAR(10) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idhorario`),
  INDEX `idx_horario_clase_idclase` (`idclase` ASC) VISIBLE,
  CONSTRAINT `fk_horario_clase_clase`
    FOREIGN KEY (`idclase`)
    REFERENCES `Universidad`.`clase` (`idclase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`nota_clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`nota_clase` (
  `idnota` VARCHAR(38) NOT NULL,
  `idclase` VARCHAR(38) NOT NULL,
  `estudiante_id` VARCHAR(38) NOT NULL,
  `nota` INT NOT NULL,
  `regular` TINYINT(1) NOT NULL DEFAULT 0,
  `promocion` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `clase_idclase` VARCHAR(38) NOT NULL,
  PRIMARY KEY (`idnota`, `clase_idclase`),
  INDEX `idx_nota_clase_idclase` (`idclase` ASC) VISIBLE,
  INDEX `idx_nota_clase_estudiante` (`estudiante_id` ASC) VISIBLE,
  INDEX `fk_nota_clase_clase1_idx` (`clase_idclase` ASC) VISIBLE,
  CONSTRAINT `fk_nota_clase_clase`
    FOREIGN KEY (`idclase`)
    REFERENCES `Universidad`.`clase` (`idclase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_nota_clase_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `Universidad`.`estudiante` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_nota_clase_clase1`
    FOREIGN KEY (`clase_idclase`)
    REFERENCES `Universidad`.`clase` (`idclase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`trabajo` (
  `empleado_id` VARCHAR(38) NOT NULL,
  `delegacion_id` VARCHAR(38) NOT NULL,
  `dia` DATE NOT NULL,
  `horaEntrada` TIME NOT NULL,
  `horaSalida` TIME NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `sueldo` DECIMAL(10,2) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`empleado_id`, `dia`),
  INDEX `idx_trabajo_delegacion` (`delegacion_id` ASC) VISIBLE,
  INDEX `idx_trabajo_dia` (`dia` ASC) VISIBLE,
  CONSTRAINT `fk_trabajo_empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Universidad`.`empleado` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trabajo_delegacion`
    FOREIGN KEY (`delegacion_id`)
    REFERENCES `Universidad`.`delegacion` (`iddelegacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trabajo_dia`
    FOREIGN KEY (`dia`)
    REFERENCES `Universidad`.`dia` (`fecha`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Universidad`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`examen` (
  `dia` DATE NOT NULL,
  `tipo` ENUM('Parcial', 'Final', 'Recuperatorio') NOT NULL,
  `estudiante_id` VARCHAR(38) NOT NULL,
  `profesor_id` VARCHAR(38) NOT NULL,
  `aula` VARCHAR(10) NOT NULL,
  `horaEntrada` TIME NOT NULL,
  `horaSalida` TIME NOT NULL,
  `promocion` TINYINT(1) NOT NULL DEFAULT 0,
  `regularidad` TINYINT(1) NOT NULL DEFAULT 0,
  `nota` INT NOT NULL DEFAULT 0,
  `materia_id` VARCHAR(38) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`dia`, `estudiante_id`, `materia_id`),
  INDEX `idx_examen_estudiante` (`estudiante_id` ASC) VISIBLE,
  INDEX `idx_examen_profesor` (`profesor_id` ASC) VISIBLE,
  INDEX `idx_examen_materia` (`materia_id` ASC) VISIBLE,
  CONSTRAINT `fk_examen_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `Universidad`.`estudiante` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_examen_profesor`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `Universidad`.`profesor` (`empleado_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_examen_materia`
    FOREIGN KEY (`materia_id`)
    REFERENCES `Universidad`.`materia` (`idmateria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_examen_dia`
    FOREIGN KEY (`dia`)
    REFERENCES `Universidad`.`dia` (`fecha`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8 PARTITION BY RANGE(YEAR(dia)) PARTITIONS 4( PARTITION p2023 VALUES LESS THAN (2024),  PARTITION p2024 VALUES LESS THAN (2025),  PARTITION p2025 VALUES LESS THAN (2026),  PARTITION pMax VALUES LESS THAN (MAX_VALUE)) ;


-- -----------------------------------------------------
-- Table `Universidad`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidad`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `hash_password` VARCHAR(255) NOT NULL,
  `rol` ENUM('admin', 'profesor', 'estudiante', 'administrativo') NOT NULL,
  `persona_id` VARCHAR(38) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `uidx_usuario_nombre` (`usuario` ASC) VISIBLE,
  INDEX `idx_usuario_persona` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `Universidad`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `Universidad` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
